name: 'Action_LeanWRT_composite'
description: 'Action'
inputs:
  ROUTER_MODEL:  
    description: 'MODEL'
    required: true
    default: 'EA8500'
  COMPILE_CONFIG: 
    description: 'CONFIG'
    required: true
    default: 'EA8500-20240424-remove-igmpproxy'
  FILES_CONFIG: 
    description: 
    required: false
    default: 'public'
runs:
  using: "composite"
  steps:
    - name: Compile      
      shell: bash
      env:
        ROUTER_MODEL.: ${{ inputs.ROUTER_MODEL }}   
        COMPILE_CONFIG: ${{ inputs.COMPILE_CONFIG }} 
        FILES_CONFIG: ${{ inputs.FILES_CONFIG }} 
      run:  |
          echo "当前工作目录"
          pwd          
          echo '当前执行步骤：1-下载LeanWRT仓库'
          git clone --depth 1  https://github.com/thinkcyy/OpenWRT-Action OpenWRT-Action 
          #git clone --depth 1  https://github.com/coolsnowwolf/lede -b master --single-branch ./OpenWRT-Action/openwrt
          git clone --depth 1  https://github.com/thinkcyy/LeanWRT -b master --single-branch ./OpenWRT-Action/openwrt
          tree -L 3
          
          echo '当前执行步骤：2-处理Package'
          cd ./OpenWRT-Action
          echo "当前工作目录"
          pwd 
          tree -L 3
          chmod +x ./LeanWRT/scripts/*.sh
          cp -vr ./LeanWRT/config/$COMPILE_CONFIG.config ./LeanWRT/config/config-$ROUTER_MODEL.config
          ./LeanWRT/scripts/prepare.sh
          
          echo '当前执行步骤：3-添加自定义配置files'
          echo "当前工作目录"
          pwd          
          if [ "$FILES_CONFIG" != 'public' ] ; then
             echo "files版本为$FILES_CONFIG"             
             echo "-正在复制common"
             cp -vr ../openwrt-config/common/files ./openwrt/
             echo "-正在复制common-${{ env.FILES_CONFIG }}"
             cp -vr ../openwrt-config/common/$FILES_CONFIG/files ./openwrt/
             echo "-正在复制${{ env.ROUTER_MODEL }}-common"
             cp -vr ../openwrt-config/$ROUTER_MODEL/common/files ./openwrt/
             echo "-正在复制${{ env.ROUTER_MODEL }}-${{ env.FILES_CONFIG }}"
             cp -vr ../openwrt-config/$ROUTER_MODEL/$FILES_CONFIG/files ./openwrt/
             chmod +x ./openwrt/files/etc/tinc/tincvpn/tinc-up
             chmod +x ./openwrt/files/etc/tinc/tincvpn/tinc-down
             echo '-修改版本号'
             sed -i 's/R23.8.23/R23.8.23-${{ env.FILES_CONFIG }}/g' ./openwrt/package/lean/default-settings/files/zzz-default-settings 
             cat ./openwrt/package/lean/default-settings/files/zzz-default-settings | grep DISTRIB_REVISION
             echo '-files文件总览：'
             tree ./openwrt/files
          else
             echo '-当前为public版本，跳过'
          fi          
          
          echo '当前执行步骤：4-编译'
          cd ./openwrt
          echo '当前执行步骤：4.1-下载'
          make download -j$(nproc)
          echo '当前执行步骤：4.2-编译'
          make -j$(nproc) || make -j1 V=s
          
          echo '当前执行步骤：5-打标'
          if [ "$FILES_CONFIG" != 'public' ] ; then
             tag_name=$COMPILE_CONFIG-$FILES_CONFIG
          else
             tag_name=$COMPILE_CONFIG
          fi
          tag_name=$tag_name-$(date +%Y%m%d-%H%M)
          echo $tag_name
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV  

    - name: Organize files      
      shell: bash
      run: |                             
          echo '当前执行步骤：6-组织产出文件'
          echo "当前工作目录"
          pwd
          df -h
          cd ./OpenWRT-Action
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*sysupgrade*") ./artifact/
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*.buildinfo") ./artifact/
          cp -vr ./openwrt/.config ./artifact/defconfig-$COMPILE_CONFIG.config
          cd ./artifact/
          rename 's/sysupgrade.bin/sysupgrade-${{ env.TAG_NAME }}.bin/' *
          ls -Ahl
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt-${{ env.TAG_NAME }}
        path: ./OpenWRT-Action/artifact/
