name: 'Action_OpenWrt_composite'
description: 'Action'
inputs:
  ROUTER_MODEL:  
    description: 'MODEL'
    required: true
    default: 'EA8500'
  COMPILE_CONFIG: 
    description: 'CONFIG'
    required: true
    default: 'EA8500-20240524-23.05-init'
  IMAGEBUILDER: 
    description: 'IMAGEBUILDER'
    required: false
    default: 'n'
  FILES_CONFIG: 
    description: 
    required: false
    default: 'public'
  OP_REPO: 
    description: 
    required: false
    default: 'thinkcyy/OpenWrt'    
  REPO_BRANCH: 
    description: 
    required: false
    default: 'master' 
  REPO_DEPTH: 
    description: 
    required: false
    default: 'all'
  REPO_COMMIT: 
    description: 
    required: false
    default: 'latest' 
  REPO_TAG: 
    description: 
    required: false
    default: 'none'
  REPO_TYPE: 
    description: 
    required: false
    default: 'OpenWRT'     
runs:
  using: "composite"
  steps:
    - name: Compile      
      shell: bash
      env:
        ROUTER_MODEL: ${{ inputs.ROUTER_MODEL }}   
        COMPILE_CONFIG: ${{ inputs.COMPILE_CONFIG }} 
        FILES_CONFIG: ${{ inputs.FILES_CONFIG }} 
        REPO_TYPE: ${{ inputs.REPO_TYPE }}
      run:  |          
          echo "当前工作目录"
          pwd          
          echo '当前执行步骤：1-下载OpenWrt仓库'
          git clone --depth 1  https://github.com/thinkcyy/OpenWRT-Action OpenWRT-Action 
          #git clone --depth 1  https://github.com/coolsnowwolf/lede -b master --single-branch ./OpenWRT-Action/openwrt
          git clone $([[ ${{ inputs.REPO_COMMIT }} = 'latest' ]] && echo --depth 1 || echo ) https://github.com/${{ inputs.OP_REPO }} -b ${{ inputs.REPO_BRANCH }} --single-branch ./OpenWRT-Action/openwrt
          cd ./OpenWRT-Action/openwrt
          $([[ ${{ inputs.REPO_COMMIT }} != 'latest' ]] && echo git checkout ${{ inputs.REPO_COMMIT }} || echo )
          COMMITHASH=$(git rev-parse --short HEAD)
          #默认设置
          mkdir -p ./package/thinkcy
          cp -vr ../${{ inputs.REPO_TYPE }}/thinkcy-settings ./package/thinkcy
          cd ../../
          tree -L 3
          
          echo '当前执行步骤：2-处理Package'
          cd ./OpenWRT-Action
          echo "当前工作目录"
          pwd 
          tree -L 3
          chmod +x ./$REPO_TYPE/scripts/*.sh
          cp -vr ./$REPO_TYPE/config/${{ inputs.COMPILE_CONFIG }}.config ./$REPO_TYPE/config/config-${{ inputs.ROUTER_MODEL }}.config
          #cp -vr ./$REPO_TYPE/config/${{ inputs.COMPILE_CONFIG }}.config ./openwrt/.config
          echo "prepare.sh内容"
          cat ./$REPO_TYPE/scripts/prepare.sh
          ./$REPO_TYPE/scripts/prepare.sh          
          
          echo "当前工作目录"
          pwd
          
          echo '当前执行步骤：3-修改版本号'
          if [ "${{ inputs.IMAGEBUILDER }}" = 'y' ] ; then
               sed -i "s|REVISION_tobeupdated|ImageBuilder-${{ inputs.REPO_BRANCH }}-$COMMITHASH-$(date +%Y%m%d)|g" ./openwrt/package/thinkcy/thinkcy-settings/files/99-thinkcy-settings 
               sed -i "s|DESCRIPTION_tobeupdated|ImageBuilder-${{ inputs.REPO_BRANCH }}-$COMMITHASH-$(date +%Y%m%d)|g" ./openwrt/package/thinkcy/thinkcy-settings/files/99-thinkcy-settings 
          else          
               sed -i "s|REVISION_tobeupdated|${{ inputs.COMPILE_CONFIG }}-${{ inputs.FILES_CONFIG }}-${{ inputs.REPO_BRANCH }}-$COMMITHASH-$(date +%Y%m%d)|g" ./openwrt/package/thinkcy/thinkcy-settings/files/99-thinkcy-settings 
               sed -i "s|DESCRIPTION_tobeupdated|${{ inputs.COMPILE_CONFIG }}-${{ inputs.FILES_CONFIG }}-${{ inputs.REPO_BRANCH }}-$COMMITHASH-$(date +%Y%m%d)|g" ./openwrt/package/thinkcy/thinkcy-settings/files/99-thinkcy-settings 
          fi
          
          echo '当前执行步骤：4-添加自定义配置files'
          if [ "${{ inputs.FILES_CONFIG }}" != 'public' ] ; then
             # 忽略错误
             set +e
             echo "files版本为${{ inputs.FILES_CONFIG }}"             
             echo "-正在复制common"
             cp -vr ../openwrt-config/common/files ./openwrt/
             echo "-正在复制common-${{ env.FILES_CONFIG }}"
             cp -vr ../openwrt-config/common/${{ inputs.FILES_CONFIG }}/files ./openwrt/
             echo "-正在复制${{ env.ROUTER_MODEL }}-common"
             cp -vr ../openwrt-config/${{ inputs.ROUTER_MODEL }}/common/files ./openwrt/
             echo "-正在复制${{ env.ROUTER_MODEL }}-${{ env.FILES_CONFIG }}"
             cp -vr ../openwrt-config/${{ inputs.ROUTER_MODEL }}/${{ inputs.FILES_CONFIG }}/files ./openwrt/
             echo '-处理文件权限'
             chmod +x ./openwrt/files/etc/tinc/tincvpn/tinc-up
             chmod +x ./openwrt/files/etc/tinc/tincvpn/tinc-down
             chmod 400 ./openwrt/files/etc/dropbear/authorized_keys
             echo '-files文件总览：'
             tree ./openwrt/files             

             cat ./openwrt/package/thinkcy/thinkcy-settings/files/99-thinkcy-settings | grep DISTRIB_REVISION     
             cat ./openwrt/package/thinkcy/thinkcy-settings/files/99-thinkcy-settings | grep DESCRIPTION 
             echo '-向后调整tinc服务启动次序'             
             sed -i 's|START=42|START=99|g' ./openwrt/feeds/packages/net/tinc/files/tinc.init
             # 遇错退出
             set -e
          else
             echo '-当前为public版本，跳过'
          fi                       
          
          echo '当前执行步骤：5-编译'
          cd ./openwrt
          echo '当前执行步骤：5.1-下载'
          make download -j$(nproc)
          echo '当前执行步骤：5.2-编译'
          make -j$(nproc) || make -j1 V=s
          # make V=s; while [ $(($?)) -ne 0 ]; do make V=s; done
          
          echo '当前执行步骤：6-打标'
          if [ "${{ inputs.FILES_CONFIG }}" != 'public' ] ; then
             tag_name=${{ inputs.COMPILE_CONFIG }}-${{ inputs.FILES_CONFIG }}
          else
             tag_name=${{ inputs.COMPILE_CONFIG }}
          fi
          
          tag_name=$tag_name-$(date +%Y%m%d-%H%M)-${{ inputs.REPO_BRANCH }}-$COMMITHASH
          
          echo $tag_name
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV  

    - name: Organize files      
      shell: bash
      run: |                             
          echo '当前执行步骤：7-组织产出文件'          
          cd ./OpenWRT-Action
          echo "targets产出文件："
          tree  ./openwrt/bin/targets/
          rm -rf ./artifact/
          mkdir -p ./artifact/

          echo '当前执行步骤：7.1-组织配置文件：'
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*.buildinfo") ./artifact/
          cp -vr ./openwrt/.config ./artifact/defconfig-${{ env.TAG_NAME }}.config

          echo '当前执行步骤：7.2-组织bin文件：'
          if [ "${{ inputs.IMAGEBUILDER }}" = 'y' ] ; then
             # cp -vr ./openwrt/bin/ ./artifact/ 
             cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*imagebuilder*") ./artifact/             
             cd ./artifact/
             rename 's/.tar.xz/-${{ env.TAG_NAME }}.tar.xz/' *
             tag_name=Imagebuilder-${{ env.TAG_NAME }} 
             echo $tag_name
             echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
          else
             cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*sysupgrade*") ./artifact/                                   
             cd ./artifact/
             rename 's/sysupgrade.bin/sysupgrade-${{ env.TAG_NAME }}.bin/' *
          fi           

          echo '-产出文件总览：'
          ls -hl 
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: ${{ inputs.REPO_TYPE }}-${{ env.TAG_NAME }}
        path: ./OpenWRT-Action/artifact/
        
    - name: Addtional bin for release      
      shell: bash
      run: |                             
          echo '当前执行步骤：8-添加额外发布文件'    
          cd ./OpenWRT-Action
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*sdk*") ./artifact/
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*toolchain*") ./artifact/
